In [3]:
import numpy as np

In [3]:
benimDizim = np.arange(0,15)

In [4]:
benimDizim[3:8] = -5

In [5]:
benimDizim

array([ 0,  1,  2, -5, -5, -5, -5, -5,  8,  9, 10, 11, 12, 13, 14])

In [6]:
baskaDizi = np.arange(5,30)

In [7]:
slicingDizisi = baskaDizi[4:9]

In [8]:
slicingDizisi

array([ 9, 10, 11, 12, 13])

In [9]:
slicingDizisi[:] = 700

In [12]:
ornekDizi = np.arange(1,20)

In [13]:
ornekDiziKopyası = ornekDizi.copy()

In [14]:
ornekDiziKopyasınınKopyası = ornekDiziKopyası[3:6]

In [16]:
ornekDiziKopyasınınKopyası[:] = 300

## matrix

In [1]:
yeniListe = [[0,1,2,3,4],[5,6,7,8,9],[10,11,12,13,14],[15,16,17,18,19],[20,21,22,23,24]]

In [4]:
yeniMatrix = np.array(yeniListe)

In [5]:
yeniMatrix[[4,2,0]]

array([[20, 21, 22, 23, 24],
       [10, 11, 12, 13, 14],
       [ 0,  1,  2,  3,  4]])

## operasyonlar

In [6]:
yeniBirDizi = np.random.randint(1,100,20)

In [7]:
yeniBirDizi

array([70, 71,  8,  9, 29, 93, 63, 53,  4, 92, 38, 93, 36, 44, 54, 51, 78,
       11, 90, 16])

In [8]:
yeniBirDizi > 24

array([ True,  True, False, False,  True,  True,  True,  True, False,
        True,  True,  True,  True,  True,  True,  True,  True, False,
        True, False])

In [9]:
sonucDizisi = yeniBirDizi > 24

In [11]:
sonucDizisi 

array([ True,  True, False, False,  True,  True,  True,  True, False,
        True,  True,  True,  True,  True,  True,  True,  True, False,
        True, False])

In [12]:
yeniBirDizi[sonucDizisi]

array([70, 71, 29, 93, 63, 53, 92, 38, 93, 36, 44, 54, 51, 78, 90])

In [13]:
yeniBirDizi[yeniBirDizi > 24]

array([70, 71, 29, 93, 63, 53, 92, 38, 93, 36, 44, 54, 51, 78, 90])

In [14]:
sonDizi = np.arange(0,24)

In [15]:
sonDizi + sonDizi

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46])

In [16]:
np.sqrt(sonDizi)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739,
       3.87298335, 4.        , 4.12310563, 4.24264069, 4.35889894,
       4.47213595, 4.58257569, 4.69041576, 4.79583152])